=== main9471/main9471.github.io/branches.dtd
<!ELEMENT branches(address+)>
<!ELEMENT address (name, phone, hours, url)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT hours (#PCDATA)>

=== main9471/main9471.github.io/branches.xml
<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE branches SYSTEM "branches.dtd">
<branches>
    <address>
        <name>76 Devonshire St, Surry Hills NSW</name>
        <phone>02 9211 1234</phone>
        <hours>Mon-Fri:6:00 to 14:30,Sat-Sun:7:00 to 15:00</hours>
        <url>https://maps.app.goo.gl/iDFDPRVzKLEk1GJP8</url>
    </address>
     <address>
        <name>451 Pitt St,Haymarket Sydney, NSW</name>
        <phone>02 9262 5678</phone>
        <hours>Mon-Fri:6:00 to 16:00,Sat-Sun:7:00 to 15:00</hours>
        <url>https://maps.app.goo.gl/uMQAYJCdvRHu4HEr8</url>
    </address>
     <address>
        <name>31 Alfred Street, Circular Quay, NSW</name>
        <phone>02 8971 9101</phone>
        <hours>Mon-Fri:6:00 to 16:00,Sat-Sun:7:00 to 15:00</hours>
        <url>https://maps.app.goo.gl/eZA4AJHBH7mncYoK6</url>
    </address>
</branches>
